version: '3'
services:
  garwan:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    tty: true
    ports:
      - 8080:8080
    command:  bash -c "java -jar garwan-0.0.1-SNAPSHOT.jar"
